# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhguMFvHK6K0DzyRC1GmlDUyZWQ3yQkG
"""

# main.py

from password_security import check_password_security
from authentication import check_2fa
from privacy_survey import privacy_awareness_survey
from phishing_test import phishing_test
from cloud_security import cloud_security_check
from authentication import get_input_with_validation

def run_security_check():
    print("개인정보 보안 자가진단 프로그램 시작")
    total_score = 0
    total_feedback = []

    # 1. 비밀번호 보안 점검
    password = input("비밀번호를 입력하세요: ")
    feedback, score = check_password_security(password)
    total_feedback.append(feedback)
    total_score += score

    # 2. 2단계 인증 점검
    feedback, score = check_2fa()
    total_feedback.append(feedback)
    total_score += score

    # 3. 개인정보 보호 의식 점검
    feedback, score = privacy_awareness_survey()
    total_feedback.append(feedback)
    total_score += score

    # 4. 피싱 메일 대응 테스트
    feedback, score = phishing_test()
    total_feedback.append(feedback)
    total_score += score

    # 5. 클라우드 보안 점검
    feedback, score = cloud_security_check()
    total_feedback.append(feedback)
    total_score += score

    # 결과 출력
    print("\n--- 점검 결과 ---")
    for feedback in total_feedback:
        print(feedback)

    print(f"\n전체 점수: {total_score}/5")

    # 최종 결과 평가
    if total_score == 5:
        print("완벽한 보안 상태입니다! 계속해서 좋은 보안 습관을 유지하세요.")
    elif total_score >= 4:
        print("보안 상태가 좋습니다. 계속해서 보안을 강화해주세요.")
    elif total_score >= 3:
        print("보안 상태가 괜찮습니다. 몇 가지 보안을 강화할 필요가 있습니다.")
    else:
        print("보안 상태가 취약합니다. 즉시 개선이 필요합니다.")

# 프로그램 실행
if __name__ == "__main__":
    run_security_check()

    