# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhguMFvHK6K0DzyRC1GmlDUyZWQ3yQkG
"""

# authentication.py

def get_input_with_validation(prompt, valid_responses):
    while True:
        response = input(prompt).strip()
        if response.lower() in valid_responses:
            return response.lower()
        else:
            print(f"유효한 응답이 아닙니다. 유효한 응답은 {', '.join(valid_responses)} 입니다.")

def check_2fa():
    response = get_input_with_validation("2단계 인증(2FA)을 활성화하셨나요? (예/아니오): ", ["예", "아니오"])
    if response == "예":
        return "2단계 인증(2FA)이 활성화되어 있습니다. 좋은 보안 습관입니다.", 1
    else:
        return "2단계 인증(2FA)을 활성화하는 것이 좋습니다.", 0