# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhguMFvHK6K0DzyRC1GmlDUyZWQ3yQkG
"""

# password_security.py

import re

def check_password_security(password):
    score = 0
    feedback = []

    if len(password) >= 8:
        score += 1
    else:
        feedback.append("비밀번호는 최소 8자 이상이어야 합니다.")

    if re.search(r"[A-Za-z]", password):
        score += 1
    else:
        feedback.append("비밀번호에 알파벳이 포함되어야 합니다.")

    if re.search(r"\d", password):
        score += 1
    else:
        feedback.append("비밀번호에 숫자가 포함되어야 합니다.")

    if re.search(r"[!@#$%^&*(),.?\":{}|<>]", password):
        score += 1
    else:
        feedback.append("비밀번호에 특수문자가 포함되어야 합니다.")

    if score == 4:
        return "비밀번호가 안전합니다!", 1
    else:
        return "\n".join(feedback), 0