# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lhguMFvHK6K0DzyRC1GmlDUyZWQ3yQkG
"""

# phishing_test.py

def phishing_test():
    print("피싱 메일 식별 테스트")
    email_subject = input("다음 이메일 제목을 보세요: '은행 계좌 정지 알림! 계좌를 재활성화하려면 여기를 클릭하세요.'\n이 이메일이 피싱일까요? (예/아니오): ")

    if email_subject.lower() == "예":
        return "피싱 이메일을 식별했습니다! 잘 하셨어요.", 1
    else:
        return "주의! 해당 이메일은 피싱입니다. 이메일의 출처를 항상 확인하세요.", 0